version: '3.8'

services:

  nginx:
    depends_on:
      - php
      - phpmyadmin
    image: nginx:1.21-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - phpmyadmin_data:/var/www/phpmyadmin
    working_dir: /var/www/html

       
  db:
    image: mariadb:10.2
    hostname: wp_db
    container_name: wp_db 
    ports:
      - 3313:3313
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=${MYSQL_ROOT_PASSWORD}
      interval: 5s
      retries: 10

  php:
    depends_on:
      - db
    build: 
      context: ./.docker/php
      args:
        HOST_UID: $HOST_UID
    container_name: backend 
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
       
  wp_cli:
    depends_on:
      - db
      - php
    image: wordpress:cli
    hostname: wp_cli
    container_name: wp_cli
    volumes:
      - ./src:/var/www/html
    restart: "no"
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
  
  composer:
    depends_on:
      - php
    image: composer/composer
    container_name: composer 
    ports:
      - "9001:9000"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    restart: "no"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db 
      UPLOAD_LIMIT: 226419790
    volumes:
      - phpmyadmin_data:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8081:80
        
volumes:
  db_data:
  phpmyadmin_data: